Neos:
  Neos:
    fusion:
      autoInclude:
        'Sandstorm.NeosTwoFactorAuthentication': true
    modules:
      management:
        submodules:
          twoFactorAuthentication:
            controller: 'Sandstorm\NeosTwoFactorAuthentication\Controller\BackendController'
            label: 'Sandstorm.NeosTwoFactorAuthentication:Backend:module.label'
            description: 'Sandstorm.NeosTwoFactorAuthentication:Backend:module.description'
            icon: 'fas fa-lock'

    userInterface:
      translation:
        autoInclude:
          'Sandstorm.NeosTwoFactorAuthentication':
            - '*'

  Flow:
    http:
      middlewares:
        'secondFactorRedirectMiddleware':
          middleware: 'Sandstorm\NeosTwoFactorAuthentication\Http\Middleware\SecondFactorRedirectMiddleware'
    mvc:
      routes:
        'Sandstorm.NeosTwoFactorAuthentication': true

    security:
      authentication:
        providers:
          'Neos.Neos:Backend':
            provider: Sandstorm\NeosTwoFactorAuthentication\Security\Authentication\Provider\PersistentUsernameAndPasswordWithSecondFactorProvider
            token: Sandstorm\NeosTwoFactorAuthentication\Security\Authentication\Token\UsernameAndPasswordWithSecondFactor
